// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/docs": {
    params: {};
  };
  "/about": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/docs" | "/about";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/docs.tsx": {
    id: "routes/docs";
    page: "/docs";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/docs": typeof import("./app/routes/docs.tsx");
  "routes/about": typeof import("./app/routes/about.tsx");
};